# Generated by Django 4.2 on 2023-11-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_post_author_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("JP", "Japan"),
                            ("AU", "Australia"),
                            ("DK", "Denmark"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[("F", "Free"), ("P", "Paid")], max_length=1
                    ),
                ),
                ("slug", models.SlugField()),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("price", models.FloatField(blank=True, null=True)),
                ("discount_price", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
